### ISSUE TITLE
Help：Import Error

### ISSUE THREAD

**Issue by Zouzhp3** [dyn4mik3/OrderBook#13]
I have installed orderbook by pip, but I get this error when I import it：

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\50395\Desktop\CLOB\venv\lib\site-packages\orderbook\__init__.py", line 1, in <module>
    from orderbook import OrderBook
ImportError: cannot import name 'OrderBook' from 'orderbook' (C:\Users\50395\Desktop\CLOB\venv\lib\site-packages\orderbook\__init__.py)
```

**Comment by p1m3nt** [comment]
same problem here

**Comment by alrevuelta** [comment]
Same issue

**Comment by RedAtman** [comment]
Same issue, same python3

**Comment by fredrikblau** [comment]
+1

**Comment by alexpa-89** [comment]
+1

**Comment by jfncs** [comment]
install from source
